### PR TITLE
Removed default type registration.

### PR DESCRIPTION
**Pull request by wmurray8989**
Removed default type registration.

### CODE REVIEW

**Comment by davidlandreman** [comment]
This looks good.   Guess we should wait till the other PR is merged to merge this one though

**Comment by greenarrowdb** [comment]
Shouldn't this cause a version bump so that we can tie it to a specific version of core?

**Comment by wmurray8989** [comment]
Yes. The other PR needs to be merged first. I should have made a comment saying as much. Thanks for not merging yet.

**Comment by wmurray8989** [comment]
Other PR is merged. Can you please merge this?

**Pull request merged**
